version: '3.6'
services:
  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
    ports:
    - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  app:
    build: ./
    ports:
    - "80:80"
    - "9080:9080"
    depends_on:
    - redis
    environment:
      KOANF_ENVIRONMENT: docker
      KOANF_REDIS_HOST: cache
